pipeline {
    agent any

    stages {
        stage('retrieve artifacts from github') {
            steps {
                echo 'Retrieving...'
                deleteDir()
                checkout scm
            }
        }

        stage('build the artifacts') {
            steps {
                echo 'Building...'
                dir('.build') {
                    sh 'docker-compose build --force-rm --no-cache --parallel'
                }
            }
        }

        stage('publish the artifacts') {
            steps {
                echo 'Publishing...'
                dir('.build') {
                    withCredentials([[
                        $class: 'UsernamePasswordMultiBinding',
                        credentialsId: 'AWS_ACCESS_KEY', 
                        usernameVariable: 'awsAccessKeyId', 
                        passwordVariable: 'awsSecretAccessKey']]) {
                        withEnv([
                            'AWS_ACCESS_KEY_ID=${awsAccessKeyId}', 
                            'AWS_SECRET_ACCESS_KEY=${awsSecretAccessKey}']) {
                            sh 'docker-compose push'
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            // cleanWs()
            echo 'success'
        }
        failure {
            echo 'fail'
        }
    }
}
